### PR TITLE
W-14686211: HTTP Request connector incorrect behaviour when maxConnec…

### PR DESCRIPTION
**Pull request by alopezbizon**
…tions is 1

### CODE REVIEW

**Review by fsgonz — APPROVED** [review]

**Review by fsgonz — APPROVED** [review]

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by alopezbizon** [comment]
--validate

**Comment by alopezbizon** [comment]
--validate

**Comment by alopezbizon** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Pull request merged**
